title: QuestLine
description: QuestLine is an open-source, stand-alone module that minimizes the complexity of building a robust quest system. It offers a framework to create customized quest systems that are event-driven and easily maintained.

theme: minima
markdown: kramdown
highlighter: rouge
