title: QuestLine
description: A Roblox Quest Creation Module
url: https://farfromlittle.github.io/QuestLine/
markdown: GFM
theme: minima
titles_from_headings:
  enabled: true
  strip_title: true
minima:
  skin: auto
