title: QuestLine
Author:
  Name: FarFromLittle
description: QuestLine offers a framework to create customized quest systems that are event-driven and easily maintained.
og_image: Q.png

theme: minima
markdown: GFM
highlighter: rouge

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
